var contacts = [
    {
        'name': 'Супонев Александр Михайлович',
        'photo': '../../img/users/0004.jpg',
        'rank': '2 дан',
        'vk': 'https://vk.com/id60193742',
        'position': 'Руководитель по связям с международными организациями го',
        'phone': '+37529-564-53-88',
        'mail': 'bgf_minsk@hotmail.com',
    },
    {
        'name': 'Бусько Илья Владимирович',
        'photo': '../../img/users/0001.jpg',
        'rank': '2 дан',
        'vk': 'https://vk.com/id41175',
        'position': 'Разработчик и руководитель сайта федерации го Беларуси',
        'phone': '+7-911-963-26-80',
        'mail': 'trassae95st@mail.ru',
    },
    {
        'name': 'Грунковский Юрий Анатольевич',
        'photo': '../../img/users/0003.jpg',
        'rank': '2 кю',
        'vk': 'https://vk.com/id31645800',
        'position': 'Организатор турниров го в Минске',
        'phone': '+37529-369-92-94',
        'mail': '',
    },
    {
        'name': 'Герасютин Никита Эдуардович',
        'photo': '../../img/users/0002.jpg',
        'rank': '1 кю',
        'vk': 'https://vk.com/id52172986',
        'position': 'Капитан команды Беларуси в чемпионатах Европы',
        'phone': '',
        'mail': '',
    },
    {
        'name': 'Зиновенков Евгений Викторович',
        'photo': '../../img/users/0005.jpg',
        'rank': '3 кю',
        'vk': 'https://vk.com/e.zinovenkov',
        'position': 'Руководитель детского клуба го в СШ№9 г. Минска',
        'phone': '+37529-707-79-85',
        'mail': '',
    },
    {
        'name': 'Илькевич Анастасия',
        'photo': '../../img/users/0006.jpg',
        'rank': '5 кю',
        'vk': 'https://vk.com/id147790741',
        'position': 'Контактное лицо по связям с Литовской федерацией го',
        'phone': '',
        'mail': '',
    },
    {
        'name': 'Пивнев Руслан Михайлович',
        'photo': '../../img/users/0007.jpg',
        'rank': '7 кю',
        'vk': 'https://vk.com/minsk_gogamer',
        'position': 'Руководитель секции го HAGAKURE',
        'phone': '+37525-968-20-68',
        'mail': 'minskgogame@gmail.com',
    },
]