class Country {}

Country.flag_sssr = "img/flags/normal/sssr.gif";
Country.flag_sssr_m = "img/flags/mini/sssr.gif";
Country.flag_yu = "img/flags/normal/yu.jpg";
Country.flag_yu_m = "img/flags/mini/yu.jpg";
Country.flag_belarus = "img/flags/normal/by.png";
Country.flag_belarus_m = "img/flags/mini/by.png";
Country.flag_cyprus = "img/flags/normal/cy.png";
Country.flag_cyprus_m = "img/flags/mini/cy.png";
Country.flag_spain = "img/flags/normal/es.png";
Country.flag_spain_m = "img/flags/mini/es.png";
Country.flag_bulgaria = "img/flags/normal/bg.png";
Country.flag_bulgaria_m = "img/flags/mini/bg.png";
Country.flag_portugal = "img/flags/normal/pt.png";
Country.flag_portugal_m = "img/flags/mini/pt.png";
Country.flag_iceland = "img/flags/normal/is.png";
Country.flag_iceland_m = "img/flags/mini/is.png";
Country.flag_kazakhstan = "img/flags/normal/kz.png";
Country.flag_kazakhstan_m = "img/flags/mini/kz.png";
Country.flag_georgia = "img/flags/normal/ge.png";
Country.flag_georgia_m = "img/flags/mini/ge.png";
Country.flag_morocco = "img/flags/normal/ma.png";
Country.flag_morocco_m = "img/flags/mini/ma.png";
Country.flag_south_korea = "img/flags/normal/kr.png";
Country.flag_south_korea_m = "img/flags/mini/kr.png";
Country.flag_chine = "img/flags/normal/cn.png";
Country.flag_chine_m = "img/flags/mini/cn.png";
Country.flag_usa = "img/flags/normal/us.png";
Country.flag_usa_m = "img/flags/mini/us.png";
Country.flag_hungary = "img/flags/normal/hu.png";
Country.flag_hungary_m = "img/flags/mini/hu.png";
Country.flag_ukraine = "img/flags/normal/ua.png";
Country.flag_ukraine_m = "img/flags/mini/ua.png";
Country.flag_canada = "img/flags/normal/ca.png";
Country.flag_canada_m = "img/flags/mini/ca.png";
Country.flag_indonezia = "img/flags/normal/id.png";
Country.flag_indonezia_m = "img/flags/mini/id.png";
Country.flag_japan = "img/flags/normal/jp.png";
Country.flag_japan_m = "img/flags/mini/jp.png";
Country.flag_france = "img/flags/normal/fr.png";
Country.flag_france_m = "img/flags/mini/fr.png";
Country.flag_new_zeland = "img/flags/normal/nz.png";
Country.flag_new_zeland_m = "img/flags/mini/nz.png";
Country.flag_vietnam = "img/flags/normal/vn.png";
Country.flag_vietnam_m = "img/flags/mini/vn.png";
Country.flag_netherlands = "img/flags/normal/nl.png";
Country.flag_netherlands_m = "img/flags/mini/nl.png";
Country.flag_poland = "img/flags/normal/pl.png";
Country.flag_poland_m = "img/flags/mini/pl.png";
Country.flag_czechia = "img/flags/normal/cz.png";
Country.flag_czechia_m = "img/flags/mini/cz.png";
Country.flag_izrail = "img/flags/normal/il.png";
Country.flag_izrail_m = "img/flags/mini/il.png";
Country.flag_thailand = "img/flags/normal/th.png";
Country.flag_thailand_m = "img/flags/mini/th.png";
Country.flag_croatia = "img/flags/normal/hr.png";
Country.flag_croatia_m = "img/flags/mini/hr.png";
Country.flag_italy = "img/flags/normal/it.png";
Country.flag_italy_m = "img/flags/mini/it.png";
Country.flag_russia = "img/flags/normal/ru.png";
Country.flag_russia_m = "img/flags/mini/ru.png";
Country.flag_germany = "img/flags/normal/de.png";
Country.flag_germany_m = "img/flags/mini/de.png";
Country.flag_australia = "img/flags/normal/au.png";
Country.flag_australia_m = "img/flags/mini/au.png";
Country.flag_belgium = "img/flags/normal/be.png";
Country.flag_belgium_m = "img/flags/mini/be.png";
Country.flag_england = "img/flags/normal/gb.png";
Country.flag_england_m = "img/flags/mini/gb.png";
Country.flag_finland = "img/flags/normal/fi.png";
Country.flag_finland_m = "img/flags/mini/fi.png";
Country.flag_slovenia = "img/flags/normal/si.png";
Country.flag_slovenia_m = "img/flags/mini/si.png";
Country.flag_chili = "img/flags/normal/cl.png";
Country.flag_chili_m = "img/flags/mini/cl.png";
Country.flag_serbia = "img/flags/normal/rs.png";
Country.flag_serbia_m = "img/flags/mini/rs.png";
Country.flag_argentina = "img/flags/normal/ar.png";
Country.flag_argentina_m = "img/flags/mini/ar.png";
Country.flag_slovakia = "img/flags/normal/sk.png";
Country.flag_slovakia_m = "img/flags/mini/sk.png";
Country.flag_litva = "img/flags/normal/lt.png";
Country.flag_litva_m = "img/flags/mini/lt.png";
Country.flag_ireland = "img/flags/normal/ie.png";
Country.flag_ireland_m = "img/flags/mini/ie.png";
Country.flag_malaizia = "img/flags/normal/my.png";
Country.flag_malaizia_m = "img/flags/mini/my.png";
Country.flag_ruminia = "img/flags/normal/ro.png";
Country.flag_ruminia_m = "img/flags/mini/ro.png";
Country.flag_dania = "img/flags/normal/dk.png";
Country.flag_dania_m = "img/flags/mini/dk.png";
Country.flag_brazil = "img/flags/normal/br.png";
Country.flag_brazil_m = "img/flags/mini/br.png";
Country.flag_norway = "img/flags/normal/no.png";
Country.flag_norway_m = "img/flags/mini/no.png";
Country.flag_sweden = "img/flags/normal/se.png";
Country.flag_sweden_m = "img/flags/mini/se.png";
Country.flag_columbia = "img/flags/normal/co.png";
Country.flag_columbia_m = "img/flags/mini/co.png";
Country.flag_mexico = "img/flags/normal/mx.png";
Country.flag_mexico_m = "img/flags/mini/mx.png";
Country.flag_nepal = "img/flags/normal/np.png";
Country.flag_nepal_m = "img/flags/mini/np.png";
Country.flag_swiz = "img/flags/normal/ch.png";
Country.flag_swiz_m = "img/flags/mini/ch.png";
Country.flag_south_africa = "img/flags/normal/za.png";
Country.flag_south_africa_m = "img/flags/mini/za.png";
Country.flag_austria = "img/flags/normal/at.png";
Country.flag_austria_m = "img/flags/mini/at.png";
Country.flag_gvatemala = "img/flags/normal/gt.png";
Country.flag_gvatemala_m = "img/flags/mini/gt.png";
Country.flag_turkie = "img/flags/normal/tr.png";
Country.flag_turkie_m = "img/flags/mini/tr.png";
Country.flag_mongolia = "img/flags/normal/mn.png";
Country.flag_mongolia_m = "img/flags/mini/mn.png";
Country.flag_filippini = "img/flags/normal/ph.png";
Country.flag_filippini_m = "img/flags/mini/ph.png";
Country.flag_azerb = "img/flags/normal/az.png";
Country.flag_azerb_m = "img/flags/mini/az.png";
Country.flag_india = "img/flags/normal/in.png";
Country.flag_india_m = "img/flags/mini/in.png";
Country.flag_brunei = "img/flags/normal/bn.png";
Country.flag_brunei_m = "img/flags/mini/bn.png";
Country.flag_honhong = "img/flags/normal/hh.png";
Country.flag_honhong_m = "img/flags/mini/hh.png";
Country.flag_taiwan = "img/flags/normal/tw.png";
Country.flag_taiwan_m = "img/flags/mini/tw.png";
Country.flag_makao = "img/flags/normal/makao.png";
Country.flag_makao_m = "img/flags/mini/makao.png";
Country.flag_singapur = "img/flags/normal/sg.png";
Country.flag_singapur_m = "img/flags/mini/sg.png";
Country.flag_peru = "img/flags/normal/pe.png";
Country.flag_peru_m = "img/flags/mini/pe.png";
Country.flag_venezuela = "img/flags/normal/ve.png";
Country.flag_venezuela_m = "img/flags/mini/ve.png";
Country.flag_ecuador = "img/flags/normal/ec.png";
Country.flag_ecuador_m = "img/flags/mini/ec.png";
Country.flag_costa_rica = "img/flags/normal/cr.png";
Country.flag_costa_rica_m = "img/flags/mini/cr.png";
Country.flag_lux = "img/flags/normal/lu.png";
Country.flag_lux_m = "img/flags/mini/lu.png";
Country.flag_panama = "img/flags/normal/pa.png";
Country.flag_panama_m = "img/flags/mini/pa.png";
Country.flag_north_kore = "img/flags/normal/kp.png";
Country.flag_north_kore_m = "img/flags/mini/kp.png";
Country.flag_greece = "img/flags/normal/gr.png";
Country.flag_greece_m = "img/flags/mini/gr.png";


Country.cf_map_m = new Map();
Country.cf_map_m.set("СССР", Country.flag_sssr_m);
Country.cf_map_m.set("Югославия", Country.flag_yu_m);
Country.cf_map_m.set("Беларусь", Country.flag_belarus_m);
Country.cf_map_m.set("Кипр", Country.flag_cyprus_m);
Country.cf_map_m.set("Испания", Country.flag_spain_m);
Country.cf_map_m.set("Болгария", Country.flag_bulgaria_m);
Country.cf_map_m.set("Португалия", Country.flag_portugal_m);
Country.cf_map_m.set("Исландия", Country.flag_iceland_m);
Country.cf_map_m.set("Казахстан", Country.flag_kazakhstan_m);
Country.cf_map_m.set("Грузия", Country.flag_georgia_m);
Country.cf_map_m.set("Марокко", Country.flag_morocco_m);
Country.cf_map_m.set("Китай", Country.flag_chine_m);
Country.cf_map_m.set("Южная Корея", Country.flag_south_korea_m);
Country.cf_map_m.set("США", Country.flag_usa_m);
Country.cf_map_m.set("Венгрия", Country.flag_hungary_m);
Country.cf_map_m.set("Украина", Country.flag_ukraine_m);
Country.cf_map_m.set("Канада", Country.flag_canada_m);
Country.cf_map_m.set("Индонезия", Country.flag_indonezia_m);
Country.cf_map_m.set("Япония", Country.flag_japan_m);
Country.cf_map_m.set("Франция", Country.flag_france_m);
Country.cf_map_m.set("Новая Зеландия", Country.flag_new_zeland_m);
Country.cf_map_m.set("Голландия", Country.flag_netherlands_m);
Country.cf_map_m.set("Нидерланды", Country.flag_netherlands_m);
Country.cf_map_m.set("Вьетнам", Country.flag_vietnam_m);
Country.cf_map_m.set("Польша", Country.flag_poland_m);
Country.cf_map_m.set("Чехия", Country.flag_czechia_m);
Country.cf_map_m.set("Чехословакия", Country.flag_czechia_m);
Country.cf_map_m.set("Израиль", Country.flag_izrail_m);
Country.cf_map_m.set("Таиланд", Country.flag_thailand_m);
Country.cf_map_m.set("Хорватия", Country.flag_croatia_m);
Country.cf_map_m.set("Италия", Country.flag_italy_m);
Country.cf_map_m.set("Россия", Country.flag_russia_m);
Country.cf_map_m.set("Германия", Country.flag_germany_m);
Country.cf_map_m.set("Австралия", Country.flag_australia_m);
Country.cf_map_m.set("Бельгия", Country.flag_belgium_m);
Country.cf_map_m.set("Англия", Country.flag_england_m);
Country.cf_map_m.set("Великобритания", Country.flag_england_m);
Country.cf_map_m.set("Финляндия", Country.flag_finland_m);
Country.cf_map_m.set("Словения", Country.flag_slovenia_m);
Country.cf_map_m.set("Чили", Country.flag_chili_m);
Country.cf_map_m.set("Сербия", Country.flag_serbia_m);
Country.cf_map_m.set("Аргентина", Country.flag_argentina_m);
Country.cf_map_m.set("Словакия", Country.flag_slovakia_m);
Country.cf_map_m.set("Литва", Country.flag_litva_m);
Country.cf_map_m.set("Ирландия", Country.flag_ireland_m);
Country.cf_map_m.set("Малайзия", Country.flag_malaizia_m);
Country.cf_map_m.set("Румыния", Country.flag_ruminia_m);
Country.cf_map_m.set("Дания", Country.flag_dania_m);
Country.cf_map_m.set("Норвегия", Country.flag_norway_m);
Country.cf_map_m.set("Бразилия", Country.flag_brazil_m);
Country.cf_map_m.set("Швеция", Country.flag_sweden_m);
Country.cf_map_m.set("Колумбия", Country.flag_columbia_m);
Country.cf_map_m.set("Мексика", Country.flag_mexico_m);
Country.cf_map_m.set("Непал", Country.flag_nepal_m);
Country.cf_map_m.set("Швейцария", Country.flag_swiz_m);
Country.cf_map_m.set("Южная Африка", Country.flag_south_africa_m);
Country.cf_map_m.set("Австрия", Country.flag_austria_m);
Country.cf_map_m.set("Гватемала", Country.flag_gvatemala_m);
Country.cf_map_m.set("Турция", Country.flag_turkie_m);
Country.cf_map_m.set("Монголия", Country.flag_mongolia_m);
Country.cf_map_m.set("Азербайджан", Country.flag_azerb_m);
Country.cf_map_m.set("Филиппины", Country.flag_filippini_m);
Country.cf_map_m.set("Индия", Country.flag_india_m);
Country.cf_map_m.set("Бруней", Country.flag_brunei_m);
Country.cf_map_m.set("Гонконг", Country.flag_honhong_m);
Country.cf_map_m.set("Тайвань", Country.flag_taiwan_m);
Country.cf_map_m.set("Макао", Country.flag_makao_m);
Country.cf_map_m.set("Сингапур", Country.flag_singapur_m);
Country.cf_map_m.set("Эквадор", Country.flag_ecuador_m);
Country.cf_map_m.set("Венесуэла", Country.flag_venezuela_m);
Country.cf_map_m.set("Коста-Рика", Country.flag_costa_rica_m);
Country.cf_map_m.set("Северная Корея", Country.flag_north_kore_m);
Country.cf_map_m.set("Панама", Country.flag_panama_m);
Country.cf_map_m.set("Люксембург", Country.flag_lux_m);
Country.cf_map_m.set("Перу", Country.flag_peru_m);
Country.cf_map_m.set("Греция", Country.flag_greece_m);

Object.freeze(Country);