var schools = [
    {
        'name': 'Каменный дракон',
        'photo': '../../img/schools/дворец-молодежи-640.jpg',
        'city': 'Минск',
        'address': 'Старовиленский тракт/д. 41/каб. 303',
        'manager': 'Грунковский Юрий Анатольевич',
        'phone': '+37529-369-92-94',
        'vk': 'https://vk.com/club23841735',
        'ref': 'stone_dragon.php',
    },
    {
        'name': 'HAGAKURE',
        'photo': '../../img/schools/hagakure.jpg',
        'city': 'Минск',
        'address': 'ул. Короля 51 Puer Club',
        'manager': 'Пивнев Руслан Михайлович',
        'phone': '+37525-968-20-68',
        'vk': 'https://vk.com/minskgogame',
        'ref': '',
    },
    {
        'name': 'Малиновка',
        'photo': '../../img/schools/shkola9-640.jpg',
        'city': 'Минск',
        'address': 'ул.Е.Гедройца/д. 20/каб. В-110',
        'manager': 'Зиновенков Евгений Викторович',
        'phone': '+37529-707-79-85',
        'vk': 'https://vk.com/minsk_go',
        'ref': 'malinovka.php',
    },
    {
        'name': 'БрейнФорс',
        'photo': '../../img/schools/bogdanovicha-155.jpg',
        'city': 'Минск',
        'address': 'ул. Богдановича/д. 155/оф. 502',
        'manager': 'Зиновенков Евгений Викторович',
        'phone': '+37529-707-79-85',
        'vk': 'https://vk.com/minsk_go',
        'ref': 'brainforce.php',
    },
    {
        'name': 'Го в Витебске',
        'photo': '../../img/schools/vit_city.jpg',
        'city': 'Витебск',
        'address': 'ул. Гагарина 24',
        'manager': 'Бусько Илья Владимирович',
        'phone': '',
        'vk': 'https://vk.com/goinvitebsk',
        'ref': 'vitebsk.php',
    },
    {
        'name': 'Гомель',
        'photo': '../../img/icons/no_photo.png',
        'city': 'Гомель',
        'address': 'Чайный домик',
        'manager': 'Дмитрий Мокухо',
        'phone': '+37529-157-99-31',
        'vk': '',
        'ref': '',
    },
    {
        'name': 'Брест',
        'photo': '../../img/icons/no_photo.png',
        'city': 'Брест',
        'address': 'Чайный домик',
        'manager': '',
        'phone': '',
        'vk': '',
        'ref': '',
    },
    {
        'name': 'Гродно',
        'photo': '../../img/icons/no_photo.png',
        'city': 'Гродно',
        'address': 'Чайный домик',
        'manager': '',
        'phone': '',
        'vk': '',
        'ref': '',
    },
    {
        'name': 'Могилёв',
        'photo': '../../img/icons/no_photo.png',
        'city': 'Могилёв',
        'address': '',
        'manager': '',
        'phone': '',
        'vk': '',
        'ref': '',
    },
];